import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html
      lang="en"
      className="h-full antialiased"
      style={{
        "--font-outfit":
          'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      }}
    >
      <body className="min-h-full flex flex-col font-(family-name:--font-outfit)">
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
